### ISSUE TITLE
app.json问题（icon问题，已解决）

### ISSUE THREAD

**Issue by GongChang2020** [yinhao123/churu#1]

**Comment by 1163710121** [comment]
没有page login和push页面啊   app.josn报错

**Comment by yinhao123** [comment]
已经重新提交了，不好意思

**Comment by 1163710121** [comment]
谢谢！毕业设计部分功能类似，想参考一下！


| |
18846170360
邮箱：18846170360@163.com
|

Signature is customized by Netease Mail Master

在2020年02月19日 12:15，yinhao123 写道：

Closed #1.
